# Generated by Django 2.1 on 2018-08-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2048)),
                ('created_time', models.DateField()),
                ('update_time', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
