# Generated by Django 2.1 on 2018-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20180818_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
