# Generated by Django 2.1 on 2018-08-20 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20180819_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('description', models.CharField(default='', max_length=2048)),
                ('amount', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 8, 20, 6, 36, 22, 430141))),
            ],
        ),
    ]
