# Generated by Django 2.1 on 2018-08-20 08:19

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20180820_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(to='club.Profile'),
        ),
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
