# Generated by Django 2.1 on 2018-08-21 07:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20180820_0838'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('events', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='money',
            managers=[
                ('moneys', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='money',
            name='users',
            field=models.ManyToManyField(to='club.Profile'),
        ),
    ]
