# Generated by Django 2.1 on 2018-08-21 07:34

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20180821_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('description', models.CharField(max_length=2048)),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('amount', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
