# Generated by Django 2.1 on 2018-09-07 04:23

from django.db import migrations, models
import django.db.models.manager
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_outcome'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='outcome',
            managers=[
                ('outcomes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='location_time',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
    ]
