# Generated by Django 2.1 on 2018-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_change_date_fields_for_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='items',
            field=models.TextField(default='[]'),
        ),
    ]
